vibrator: Include missing fcntl header
 * Fixes:
   - error: use of undeclared identifier 'O_RDWR'
   - error: assigning to 'int' from incompatible type

Signed-off-by: jmpfbmx <jmpf.bmx@gmail.com>
Change-Id: I0cf31fc9cbfbfcc4065a2adcfd4b7a50e4c0096e